/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import components.ServiceTable;
import components.StaffManagerTable;
import dao.DichVuDAO;
import dao.NhanVienDAO;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ASUS
 */
public class DichVuForm extends javax.swing.JPanel {

    /**
     * Creates new form DichVuForm
     */
    public DichVuForm() {
        initComponents();
        refreshTable();
    }
    
    private void refreshTable(){
        ServiceTable newTable = new ServiceTable();
        DefaultTableModel newTableModel = (DefaultTableModel) newTable.getTableModel();

        TableDichVu.setModel(newTableModel);
               
        repaint();
        revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        JtfTimKiem = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableDichVu = new javax.swing.JTable();

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Sửa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Xuất");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Tìm kiếm");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        TableDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã dịch vụ", "Tên dịch vụ", "Đơn giá", "Đơn vị tính"
            }
        ));
        jScrollPane1.setViewportView(TableDichVu);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addGap(47, 47, 47)
                .addComponent(jButton2)
                .addGap(48, 48, 48)
                .addComponent(jButton3)
                .addGap(56, 56, 56)
                .addComponent(jButton4)
                .addGap(131, 131, 131)
                .addComponent(JtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(jButton6)
                .addContainerGap(72, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(JtfTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddDichVu adv=new AddDichVu();
        adv.setLocationRelativeTo(null);
        adv.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        adv.setVisible(true);
        adv.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent e) {
            refreshTable();
        }
    });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            int selectedRow = TableDichVu.getSelectedRow();

     if (selectedRow == -1) {
         javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn dịch vụ để xóa.");
         return;
     }

     String maDV = TableDichVu.getValueAt(selectedRow, 0).toString(); // Cột 0 là Mã dịch vụ

     int confirm = javax.swing.JOptionPane.showConfirmDialog(this,
             "Bạn có chắc muốn xóa dịch vụ có mã: " + maDV + "?",
             "Xác nhận xóa",
             javax.swing.JOptionPane.YES_NO_OPTION);

     if (confirm == javax.swing.JOptionPane.YES_OPTION) {
         int success = DichVuDAO.deleteDichVu(maDV); // Gọi DAO xóa theo mã dịch vụ

         if (success > 0) {
             javax.swing.JOptionPane.showMessageDialog(this, "Xóa dịch vụ thành công.");
             refreshTable(); // Cập nhật lại bảng sau khi xóa
         } else {
             javax.swing.JOptionPane.showMessageDialog(this, "Xóa thất bại. Vui lòng thử lại.");
         }
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int selectedRow = TableDichVu.getSelectedRow();

         if (selectedRow == -1) {
             JOptionPane.showMessageDialog(this, "Vui lòng chọn một dịch vụ để sửa.");
             return;
         }

         String maDV = TableDichVu.getValueAt(selectedRow, 0).toString(); // Lấy mã dịch vụ từ dòng được chọn

         model.DichVu dv = DichVuDAO.getDichVu(maDV); // Lấy đối tượng dịch vụ từ DB

         if (dv != null) {
             UpdateDichVu updateForm = new UpdateDichVu(maDV); // Truyền mã dịch vụ vào form cập nhật
             updateForm.setLocationRelativeTo(null);
             updateForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
             updateForm.setVisible(true);

             updateForm.addWindowListener(new java.awt.event.WindowAdapter() {
                 @Override
                 public void windowClosed(java.awt.event.WindowEvent e) {
                     refreshTable(); // Làm mới bảng khi form đóng
                 }
             });
         } else {
             JOptionPane.showMessageDialog(this, "Không tìm thấy thông tin dịch vụ.");
         }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       try {
        JFileChooser jFileChooser = new JFileChooser();
        jFileChooser.setDialogTitle("Chọn nơi lưu file Excel");
        jFileChooser.setSelectedFile(new File("DanhSachDichVu.xlsx"));
        int userSelection = jFileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File saveFile = jFileChooser.getSelectedFile();
            if (!saveFile.toString().toLowerCase().endsWith(".xlsx")) {
                saveFile = new File(saveFile.toString() + ".xlsx");
            }

            Workbook wb = new XSSFWorkbook();
            Sheet sheet = wb.createSheet("Danh sách dịch vụ");

            // Tạo dòng tiêu đề (header)
            Row rowCol = sheet.createRow(0);
            for (int i = 0; i < TableDichVu.getColumnCount(); i++) {
                Cell cell = rowCol.createCell(i);
                cell.setCellValue(TableDichVu.getColumnName(i));
            }

            // Ghi dữ liệu dịch vụ
            for (int j = 0; j < TableDichVu.getRowCount(); j++) {
                Row row = sheet.createRow(j + 1);
                for (int k = 0; k < TableDichVu.getColumnCount(); k++) {
                    Cell cell = row.createCell(k);
                    Object value = TableDichVu.getValueAt(j, k);
                    if (value != null) {
                        cell.setCellValue(value.toString());
                    }
                }
            }

            // Ghi workbook ra file
            try (FileOutputStream out = new FileOutputStream(saveFile)) {
                wb.write(out);
            }
            wb.close();

            // Mở file sau khi lưu
            openFile(saveFile.toString());
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String keyword = JtfTimKiem.getText().trim().toLowerCase();

        DefaultTableModel model = (DefaultTableModel) TableDichVu.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        TableDichVu.setRowSorter(sorter);

        if (keyword.isEmpty()) {
            sorter.setRowFilter(null); // Hiển thị toàn bộ
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + keyword, 1)); // Cột 1: "Tên dịch vụ"
        }
    }//GEN-LAST:event_jButton6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtfTimKiem;
    private javax.swing.JTable TableDichVu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void openFile(String toString) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
