/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import controller.CTDichVuController;
import controller.PhongController;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import model.DatPhong;

/**
 *
 * @author ASUS
 */
public class PhongForm extends javax.swing.JPanel {

    /**
     * Creates new form PhongForm
     */
    private String maDatPhong101;
    private String maKhachHang;
    private JTable TableDV;
    private PhongController phong;
    private CTDichVuController ctdichVu;
    public PhongForm() {
        this.phong=new PhongController();
        this.ctdichVu=new CTDichVuController();
        initComponents();
        if(phong.check(MaPhongP101.getText())) {
            JpnP101.setBackground(new Color(0, 143, 143));
            TinhTrangP101.setText("Tình trạng: Đang sử dụng");
            ButtonP101.setText("Thanh toán");
        }
        if(phong.check(MaPhongP201.getText())) {
            JpnP201.setBackground(new Color(0, 143, 143));
            TinhTrangP201.setText("Tình trạng: Đang sử dụng");
            ButtonP201.setText("Thanh toán");
        }
        if(phong.check(MaPhongP301.getText())) {
            JpnP301.setBackground(new Color(0, 143, 143));
            TinhTrangP301.setText("Tình trạng: Đang sử dụng");
            ButtonP301.setText("Thanh toán");
        }
        if(phong.check(MaPhongP401.getText())) {
            JpnP401.setBackground(new Color(0, 143, 143));
            TinhTrangP401.setText("Tình trạng: Đang sử dụng");
            ButtonP401.setText("Thanh toán");
        }
        if(phong.check(MaPhongP102.getText())) {
            JpnP102.setBackground(new Color(0, 143, 143));
            TinhTrangP102.setText("Tình trạng: Đang sử dụng");
            ButtonP102.setText("Thanh toán");
        }
        if(phong.check(MaPhongP202.getText())) {
            JpnP202.setBackground(new Color(0, 143, 143));
            TinhTrangP202.setText("Tình trạng: Đang sử dụng");
            ButtonP202.setText("Thanh toán");
        }
        if(phong.check(MaPhongP302.getText())) {
            JpnP302.setBackground(new Color(0, 143, 143));
            TinhTrangP302.setText("Tình trạng: Đang sử dụng");
            ButtonP302.setText("Thanh toán");
        }
        if(phong.check(MaPhongP402.getText())) {
            JpnP402.setBackground(new Color(0, 143, 143));
            TinhTrangP402.setText("Tình trạng: Đang sử dụng");
            ButtonP402.setText("Thanh toán");
        }
        if(phong.check(MaPhongP103.getText())) {
            JpnP103.setBackground(new Color(0, 143, 143));
            TinhTrangP103.setText("Tình trạng: Đang sử dụng");
            ButtonP103.setText("Thanh toán");
        }
        if(phong.check(MaPhongP203.getText())) {
            JpnP203.setBackground(new Color(0, 143, 143));
            TinhTrangP203.setText("Tình trạng: Đang sử dụng");
            ButtonP203.setText("Thanh toán");
        }
        if(phong.check(MaPhongP303.getText())) {
            JpnP303.setBackground(new Color(0, 143, 143));
            TinhTrangP303.setText("Tình trạng: Đang sử dụng");
            ButtonP303.setText("Thanh toán");
        }
        if(phong.check(MaPhongP403.getText())) {
            JpnP403.setBackground(new Color(0, 143, 143));
            TinhTrangP403.setText("Tình trạng: Đang sử dụng");
            ButtonP403.setText("Thanh toán");
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JpnP101 = new javax.swing.JPanel();
        MaPhongP101 = new javax.swing.JLabel();
        KieuPhongP101 = new javax.swing.JLabel();
        LoaiPhongP101 = new javax.swing.JLabel();
        TinhTrangP101 = new javax.swing.JLabel();
        ButtonP101 = new javax.swing.JButton();
        JpnP102 = new javax.swing.JPanel();
        MaPhongP102 = new javax.swing.JLabel();
        KieuPhongP102 = new javax.swing.JLabel();
        LoaiPhongP102 = new javax.swing.JLabel();
        TinhTrangP102 = new javax.swing.JLabel();
        ButtonP102 = new javax.swing.JButton();
        JpnP103 = new javax.swing.JPanel();
        MaPhongP103 = new javax.swing.JLabel();
        KieuPhongP103 = new javax.swing.JLabel();
        LoaiPhongP103 = new javax.swing.JLabel();
        TinhTrangP103 = new javax.swing.JLabel();
        ButtonP103 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        JpnP201 = new javax.swing.JPanel();
        MaPhongP201 = new javax.swing.JLabel();
        KieuPhongP201 = new javax.swing.JLabel();
        LoaiPhongP201 = new javax.swing.JLabel();
        TinhTrangP201 = new javax.swing.JLabel();
        ButtonP201 = new javax.swing.JButton();
        JpnP202 = new javax.swing.JPanel();
        MaPhongP202 = new javax.swing.JLabel();
        KieuPhongP202 = new javax.swing.JLabel();
        LoaiPhongP202 = new javax.swing.JLabel();
        TinhTrangP202 = new javax.swing.JLabel();
        ButtonP202 = new javax.swing.JButton();
        JpnP203 = new javax.swing.JPanel();
        MaPhongP203 = new javax.swing.JLabel();
        KieuPhongP203 = new javax.swing.JLabel();
        LoaiPhongP203 = new javax.swing.JLabel();
        TinhTrangP203 = new javax.swing.JLabel();
        ButtonP203 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        JpnP301 = new javax.swing.JPanel();
        MaPhongP301 = new javax.swing.JLabel();
        KieuPhongP301 = new javax.swing.JLabel();
        LoaiPhongP301 = new javax.swing.JLabel();
        TinhTrangP301 = new javax.swing.JLabel();
        ButtonP301 = new javax.swing.JButton();
        JpnP302 = new javax.swing.JPanel();
        MaPhongP302 = new javax.swing.JLabel();
        KieuPhongP302 = new javax.swing.JLabel();
        LoaiPhongP302 = new javax.swing.JLabel();
        TinhTrangP302 = new javax.swing.JLabel();
        ButtonP302 = new javax.swing.JButton();
        JpnP303 = new javax.swing.JPanel();
        MaPhongP303 = new javax.swing.JLabel();
        KieuPhongP303 = new javax.swing.JLabel();
        LoaiPhongP303 = new javax.swing.JLabel();
        TinhTrangP303 = new javax.swing.JLabel();
        ButtonP303 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        JpnP401 = new javax.swing.JPanel();
        MaPhongP401 = new javax.swing.JLabel();
        KieuPhongP401 = new javax.swing.JLabel();
        LoaiPhongP401 = new javax.swing.JLabel();
        TinhTrangP401 = new javax.swing.JLabel();
        ButtonP401 = new javax.swing.JButton();
        JpnP402 = new javax.swing.JPanel();
        MaPhongP402 = new javax.swing.JLabel();
        KieuPhongP402 = new javax.swing.JLabel();
        LoaiPhongP402 = new javax.swing.JLabel();
        TinhTrangP402 = new javax.swing.JLabel();
        ButtonP402 = new javax.swing.JButton();
        JpnP403 = new javax.swing.JPanel();
        MaPhongP403 = new javax.swing.JLabel();
        KieuPhongP403 = new javax.swing.JLabel();
        LoaiPhongP403 = new javax.swing.JLabel();
        TinhTrangP403 = new javax.swing.JLabel();
        ButtonP403 = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LẦU 1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        JpnP101.setBackground(new java.awt.Color(250, 140, 0));

        MaPhongP101.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaPhongP101.setForeground(new java.awt.Color(255, 255, 255));
        MaPhongP101.setText("P101");

        KieuPhongP101.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KieuPhongP101.setForeground(new java.awt.Color(255, 255, 255));
        KieuPhongP101.setText("Kiểu phòng: Giường đôi");

        LoaiPhongP101.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiPhongP101.setForeground(new java.awt.Color(255, 255, 255));
        LoaiPhongP101.setText("Loại phòng: Thường");

        TinhTrangP101.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrangP101.setForeground(new java.awt.Color(255, 255, 255));
        TinhTrangP101.setText("Tình trạng: Trống");

        ButtonP101.setBackground(new java.awt.Color(51, 51, 51));
        ButtonP101.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonP101.setForeground(new java.awt.Color(255, 255, 255));
        ButtonP101.setText("Đặt phòng");
        ButtonP101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonP101ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnP101Layout = new javax.swing.GroupLayout(JpnP101);
        JpnP101.setLayout(JpnP101Layout);
        JpnP101Layout.setHorizontalGroup(
            JpnP101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP101Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(MaPhongP101)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP101Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(JpnP101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LoaiPhongP101)
                    .addComponent(KieuPhongP101)
                    .addComponent(TinhTrangP101)
                    .addGroup(JpnP101Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(ButtonP101)))
                .addGap(48, 48, 48))
        );
        JpnP101Layout.setVerticalGroup(
            JpnP101Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP101Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaPhongP101)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KieuPhongP101)
                .addGap(12, 12, 12)
                .addComponent(LoaiPhongP101)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TinhTrangP101)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(ButtonP101)
                .addContainerGap())
        );

        JpnP102.setBackground(new java.awt.Color(250, 140, 0));
        JpnP102.setPreferredSize(new java.awt.Dimension(262, 186));

        MaPhongP102.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaPhongP102.setForeground(new java.awt.Color(255, 255, 255));
        MaPhongP102.setText("P102");

        KieuPhongP102.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KieuPhongP102.setForeground(new java.awt.Color(255, 255, 255));
        KieuPhongP102.setText("Kiểu phòng: Giường đơn");

        LoaiPhongP102.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiPhongP102.setForeground(new java.awt.Color(255, 255, 255));
        LoaiPhongP102.setText("Loại phòng: Thường");

        TinhTrangP102.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrangP102.setForeground(new java.awt.Color(255, 255, 255));
        TinhTrangP102.setText("Tình trạng: Trống");

        ButtonP102.setBackground(new java.awt.Color(51, 51, 51));
        ButtonP102.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonP102.setForeground(new java.awt.Color(255, 255, 255));
        ButtonP102.setText("Đặt phòng");
        ButtonP102.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonP102ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnP102Layout = new javax.swing.GroupLayout(JpnP102);
        JpnP102.setLayout(JpnP102Layout);
        JpnP102Layout.setHorizontalGroup(
            JpnP102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP102Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(JpnP102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TinhTrangP102)
                    .addGroup(JpnP102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP102Layout.createSequentialGroup()
                            .addComponent(MaPhongP102)
                            .addGap(97, 97, 97))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP102Layout.createSequentialGroup()
                            .addComponent(KieuPhongP102)
                            .addGap(46, 46, 46)))
                    .addGroup(JpnP102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ButtonP102)
                        .addComponent(LoaiPhongP102))))
        );
        JpnP102Layout.setVerticalGroup(
            JpnP102Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP102Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(MaPhongP102)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KieuPhongP102)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoaiPhongP102)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TinhTrangP102)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(ButtonP102)
                .addContainerGap())
        );

        JpnP103.setBackground(new java.awt.Color(250, 140, 0));

        MaPhongP103.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaPhongP103.setForeground(new java.awt.Color(255, 255, 255));
        MaPhongP103.setText("P103");

        KieuPhongP103.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KieuPhongP103.setForeground(new java.awt.Color(255, 255, 255));
        KieuPhongP103.setText("Kiểu phòng: Giường đơn");

        LoaiPhongP103.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiPhongP103.setForeground(new java.awt.Color(255, 255, 255));
        LoaiPhongP103.setText("Loại phòng: Thường");

        TinhTrangP103.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrangP103.setForeground(new java.awt.Color(255, 255, 255));
        TinhTrangP103.setText("Tình trạng: Trống");

        ButtonP103.setBackground(new java.awt.Color(51, 51, 51));
        ButtonP103.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonP103.setForeground(new java.awt.Color(255, 255, 255));
        ButtonP103.setText("Đặt phòng");
        ButtonP103.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonP103ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnP103Layout = new javax.swing.GroupLayout(JpnP103);
        JpnP103.setLayout(JpnP103Layout);
        JpnP103Layout.setHorizontalGroup(
            JpnP103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP103Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(JpnP103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP103Layout.createSequentialGroup()
                        .addGroup(JpnP103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KieuPhongP103)
                            .addComponent(TinhTrangP103)
                            .addGroup(JpnP103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(ButtonP103)
                                .addComponent(LoaiPhongP103)))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP103Layout.createSequentialGroup()
                        .addComponent(MaPhongP103)
                        .addGap(99, 99, 99))))
        );
        JpnP103Layout.setVerticalGroup(
            JpnP103Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP103Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(MaPhongP103)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KieuPhongP103)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoaiPhongP103)
                .addGap(12, 12, 12)
                .addComponent(TinhTrangP103)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonP103)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnP101, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnP102, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnP103, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnP101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnP102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnP103, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jPanel6.setBackground(new java.awt.Color(0, 153, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LẦU 2");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(94, 94, 94))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        JpnP201.setBackground(new java.awt.Color(250, 140, 0));

        MaPhongP201.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaPhongP201.setForeground(new java.awt.Color(255, 255, 255));
        MaPhongP201.setText("P201");

        KieuPhongP201.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KieuPhongP201.setForeground(new java.awt.Color(255, 255, 255));
        KieuPhongP201.setText("Kiểu phòng: Giường đơn");

        LoaiPhongP201.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiPhongP201.setForeground(new java.awt.Color(255, 255, 255));
        LoaiPhongP201.setText("Loại phòng: VIP");

        TinhTrangP201.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrangP201.setForeground(new java.awt.Color(255, 255, 255));
        TinhTrangP201.setText("Tình trạng: Trống");

        ButtonP201.setBackground(new java.awt.Color(51, 51, 51));
        ButtonP201.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonP201.setForeground(new java.awt.Color(255, 255, 255));
        ButtonP201.setText("Đặt phòng");
        ButtonP201.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonP201ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnP201Layout = new javax.swing.GroupLayout(JpnP201);
        JpnP201.setLayout(JpnP201Layout);
        JpnP201Layout.setHorizontalGroup(
            JpnP201Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP201Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpnP201Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP201Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JpnP201Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP201Layout.createSequentialGroup()
                                .addComponent(MaPhongP201)
                                .addGap(103, 103, 103))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP201Layout.createSequentialGroup()
                                .addComponent(KieuPhongP201)
                                .addGap(49, 49, 49)))
                        .addGroup(JpnP201Layout.createSequentialGroup()
                            .addGroup(JpnP201Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LoaiPhongP201)
                                .addComponent(TinhTrangP201))
                            .addGap(19, 19, 19)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP201Layout.createSequentialGroup()
                        .addComponent(ButtonP201)
                        .addGap(74, 74, 74))))
        );
        JpnP201Layout.setVerticalGroup(
            JpnP201Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP201Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaPhongP201)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KieuPhongP201)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoaiPhongP201)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TinhTrangP201)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(ButtonP201)
                .addContainerGap())
        );

        JpnP202.setBackground(new java.awt.Color(250, 140, 0));

        MaPhongP202.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaPhongP202.setForeground(new java.awt.Color(255, 255, 255));
        MaPhongP202.setText("P202");

        KieuPhongP202.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KieuPhongP202.setForeground(new java.awt.Color(255, 255, 255));
        KieuPhongP202.setText("Kiểu phòng: Giường đôi");

        LoaiPhongP202.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiPhongP202.setForeground(new java.awt.Color(255, 255, 255));
        LoaiPhongP202.setText("Loại phòng: Thường");

        TinhTrangP202.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrangP202.setForeground(new java.awt.Color(255, 255, 255));
        TinhTrangP202.setText("Tình trạng: Trống");

        ButtonP202.setBackground(new java.awt.Color(51, 51, 51));
        ButtonP202.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonP202.setForeground(new java.awt.Color(255, 255, 255));
        ButtonP202.setText("Đặt phòng");
        ButtonP202.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonP202ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnP202Layout = new javax.swing.GroupLayout(JpnP202);
        JpnP202.setLayout(JpnP202Layout);
        JpnP202Layout.setHorizontalGroup(
            JpnP202Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP202Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(JpnP202Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpnP202Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP202Layout.createSequentialGroup()
                            .addComponent(MaPhongP202)
                            .addGap(103, 103, 103))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP202Layout.createSequentialGroup()
                            .addComponent(KieuPhongP202)
                            .addGap(49, 49, 49)))
                    .addGroup(JpnP202Layout.createSequentialGroup()
                        .addGroup(JpnP202Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ButtonP202)
                            .addGroup(JpnP202Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LoaiPhongP202)
                                .addComponent(TinhTrangP202)))
                        .addGap(19, 19, 19))))
        );
        JpnP202Layout.setVerticalGroup(
            JpnP202Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP202Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaPhongP202)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KieuPhongP202)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoaiPhongP202)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TinhTrangP202)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonP202)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        JpnP203.setBackground(new java.awt.Color(250, 140, 0));

        MaPhongP203.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaPhongP203.setForeground(new java.awt.Color(255, 255, 255));
        MaPhongP203.setText("P203");

        KieuPhongP203.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KieuPhongP203.setForeground(new java.awt.Color(255, 255, 255));
        KieuPhongP203.setText("Kiểu phòng: Giường đơn");

        LoaiPhongP203.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiPhongP203.setForeground(new java.awt.Color(255, 255, 255));
        LoaiPhongP203.setText("Loại phòng: VIP");

        TinhTrangP203.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrangP203.setForeground(new java.awt.Color(255, 255, 255));
        TinhTrangP203.setText("Tình trạng: Trống");

        ButtonP203.setBackground(new java.awt.Color(51, 51, 51));
        ButtonP203.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonP203.setForeground(new java.awt.Color(255, 255, 255));
        ButtonP203.setText("Đặt phòng");
        ButtonP203.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonP203ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnP203Layout = new javax.swing.GroupLayout(JpnP203);
        JpnP203.setLayout(JpnP203Layout);
        JpnP203Layout.setHorizontalGroup(
            JpnP203Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP203Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpnP203Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP203Layout.createSequentialGroup()
                        .addGroup(JpnP203Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpnP203Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(MaPhongP203))
                            .addComponent(LoaiPhongP203)
                            .addComponent(TinhTrangP203)
                            .addComponent(KieuPhongP203))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP203Layout.createSequentialGroup()
                        .addComponent(ButtonP203)
                        .addGap(75, 75, 75))))
        );
        JpnP203Layout.setVerticalGroup(
            JpnP203Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP203Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaPhongP203)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KieuPhongP203)
                .addGap(12, 12, 12)
                .addComponent(LoaiPhongP203)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TinhTrangP203)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonP203)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnP201, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnP202, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnP203, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnP201, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnP202, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnP203, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LẦU 3");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(92, 92, 92))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        JpnP301.setBackground(new java.awt.Color(250, 140, 0));

        MaPhongP301.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaPhongP301.setForeground(new java.awt.Color(255, 255, 255));
        MaPhongP301.setText("P301");

        KieuPhongP301.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KieuPhongP301.setForeground(new java.awt.Color(255, 255, 255));
        KieuPhongP301.setText("Kiểu phòng: Giường đôi");

        LoaiPhongP301.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiPhongP301.setForeground(new java.awt.Color(255, 255, 255));
        LoaiPhongP301.setText("Loại phòng: VIP");

        TinhTrangP301.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrangP301.setForeground(new java.awt.Color(255, 255, 255));
        TinhTrangP301.setText("Tình trạng: Trống");

        ButtonP301.setBackground(new java.awt.Color(51, 51, 51));
        ButtonP301.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonP301.setForeground(new java.awt.Color(255, 255, 255));
        ButtonP301.setText("Đặt phòng");
        ButtonP301.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonP301ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnP301Layout = new javax.swing.GroupLayout(JpnP301);
        JpnP301.setLayout(JpnP301Layout);
        JpnP301Layout.setHorizontalGroup(
            JpnP301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP301Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(JpnP301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JpnP301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP301Layout.createSequentialGroup()
                                .addComponent(MaPhongP301)
                                .addGap(103, 103, 103))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP301Layout.createSequentialGroup()
                                .addComponent(KieuPhongP301)
                                .addGap(49, 49, 49)))
                        .addGroup(JpnP301Layout.createSequentialGroup()
                            .addGroup(JpnP301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LoaiPhongP301)
                                .addComponent(TinhTrangP301))
                            .addGap(19, 19, 19)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP301Layout.createSequentialGroup()
                        .addComponent(ButtonP301)
                        .addGap(74, 74, 74))))
        );
        JpnP301Layout.setVerticalGroup(
            JpnP301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP301Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaPhongP301)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KieuPhongP301)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoaiPhongP301)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TinhTrangP301)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(ButtonP301)
                .addContainerGap())
        );

        JpnP302.setBackground(new java.awt.Color(250, 140, 0));

        MaPhongP302.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaPhongP302.setForeground(new java.awt.Color(255, 255, 255));
        MaPhongP302.setText("P302");

        KieuPhongP302.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KieuPhongP302.setForeground(new java.awt.Color(255, 255, 255));
        KieuPhongP302.setText("Kiểu phòng: Giường đơn");

        LoaiPhongP302.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiPhongP302.setForeground(new java.awt.Color(255, 255, 255));
        LoaiPhongP302.setText("Loại phòng: VIP");

        TinhTrangP302.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrangP302.setForeground(new java.awt.Color(255, 255, 255));
        TinhTrangP302.setText("Tình trạng: Trống");

        ButtonP302.setBackground(new java.awt.Color(51, 51, 51));
        ButtonP302.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonP302.setForeground(new java.awt.Color(255, 255, 255));
        ButtonP302.setText("Đặt phòng");
        ButtonP302.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonP302ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnP302Layout = new javax.swing.GroupLayout(JpnP302);
        JpnP302.setLayout(JpnP302Layout);
        JpnP302Layout.setHorizontalGroup(
            JpnP302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP302Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpnP302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JpnP302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP302Layout.createSequentialGroup()
                                .addComponent(MaPhongP302)
                                .addGap(103, 103, 103))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP302Layout.createSequentialGroup()
                                .addComponent(KieuPhongP302)
                                .addGap(49, 49, 49)))
                        .addGroup(JpnP302Layout.createSequentialGroup()
                            .addGroup(JpnP302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LoaiPhongP302)
                                .addComponent(TinhTrangP302))
                            .addGap(19, 19, 19)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP302Layout.createSequentialGroup()
                        .addComponent(ButtonP302)
                        .addGap(72, 72, 72))))
        );
        JpnP302Layout.setVerticalGroup(
            JpnP302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP302Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaPhongP302)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KieuPhongP302)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoaiPhongP302)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TinhTrangP302)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonP302)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JpnP303.setBackground(new java.awt.Color(250, 140, 0));

        MaPhongP303.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaPhongP303.setForeground(new java.awt.Color(255, 255, 255));
        MaPhongP303.setText("P303");

        KieuPhongP303.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KieuPhongP303.setForeground(new java.awt.Color(255, 255, 255));
        KieuPhongP303.setText("Kiểu phòng: Giường đôi");

        LoaiPhongP303.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiPhongP303.setForeground(new java.awt.Color(255, 255, 255));
        LoaiPhongP303.setText("Loại phòng: VIP");

        TinhTrangP303.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrangP303.setForeground(new java.awt.Color(255, 255, 255));
        TinhTrangP303.setText("Tình trạng: Trống");

        ButtonP303.setBackground(new java.awt.Color(51, 51, 51));
        ButtonP303.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonP303.setForeground(new java.awt.Color(255, 255, 255));
        ButtonP303.setText("Đặt phòng");
        ButtonP303.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonP303ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnP303Layout = new javax.swing.GroupLayout(JpnP303);
        JpnP303.setLayout(JpnP303Layout);
        JpnP303Layout.setHorizontalGroup(
            JpnP303Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP303Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpnP303Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP303Layout.createSequentialGroup()
                        .addGroup(JpnP303Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpnP303Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(MaPhongP303))
                            .addComponent(LoaiPhongP303)
                            .addComponent(TinhTrangP303)
                            .addComponent(KieuPhongP303))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP303Layout.createSequentialGroup()
                        .addComponent(ButtonP303)
                        .addGap(76, 76, 76))))
        );
        JpnP303Layout.setVerticalGroup(
            JpnP303Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP303Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaPhongP303)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KieuPhongP303)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoaiPhongP303)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TinhTrangP303)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonP303)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnP301, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnP302, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnP303, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnP301, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnP302, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnP303, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jPanel8.setBackground(new java.awt.Color(0, 153, 153));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LẦU 4");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(97, 97, 97))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        JpnP401.setBackground(new java.awt.Color(250, 140, 0));

        MaPhongP401.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaPhongP401.setForeground(new java.awt.Color(255, 255, 255));
        MaPhongP401.setText("P401");

        KieuPhongP401.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KieuPhongP401.setForeground(new java.awt.Color(255, 255, 255));
        KieuPhongP401.setText("Kiểu phòng: Giường đơn");

        LoaiPhongP401.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiPhongP401.setForeground(new java.awt.Color(255, 255, 255));
        LoaiPhongP401.setText("Loại phòng: VIP");

        TinhTrangP401.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrangP401.setForeground(new java.awt.Color(255, 255, 255));
        TinhTrangP401.setText("Tình trạng: Trống");

        ButtonP401.setBackground(new java.awt.Color(51, 51, 51));
        ButtonP401.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonP401.setForeground(new java.awt.Color(255, 255, 255));
        ButtonP401.setText("Đặt phòng");
        ButtonP401.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonP401ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnP401Layout = new javax.swing.GroupLayout(JpnP401);
        JpnP401.setLayout(JpnP401Layout);
        JpnP401Layout.setHorizontalGroup(
            JpnP401Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP401Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(JpnP401Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP401Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JpnP401Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP401Layout.createSequentialGroup()
                                .addComponent(MaPhongP401)
                                .addGap(103, 103, 103))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP401Layout.createSequentialGroup()
                                .addComponent(KieuPhongP401)
                                .addGap(49, 49, 49)))
                        .addGroup(JpnP401Layout.createSequentialGroup()
                            .addGroup(JpnP401Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LoaiPhongP401)
                                .addComponent(TinhTrangP401))
                            .addGap(19, 19, 19)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP401Layout.createSequentialGroup()
                        .addComponent(ButtonP401)
                        .addGap(74, 74, 74))))
        );
        JpnP401Layout.setVerticalGroup(
            JpnP401Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP401Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaPhongP401)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KieuPhongP401)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoaiPhongP401)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TinhTrangP401)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(ButtonP401)
                .addContainerGap())
        );

        JpnP402.setBackground(new java.awt.Color(250, 140, 0));

        MaPhongP402.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaPhongP402.setForeground(new java.awt.Color(255, 255, 255));
        MaPhongP402.setText("P402");

        KieuPhongP402.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KieuPhongP402.setForeground(new java.awt.Color(255, 255, 255));
        KieuPhongP402.setText("Kiểu phòng: Giường đôi");

        LoaiPhongP402.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiPhongP402.setForeground(new java.awt.Color(255, 255, 255));
        LoaiPhongP402.setText("Loại phòng: VIP");

        TinhTrangP402.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrangP402.setForeground(new java.awt.Color(255, 255, 255));
        TinhTrangP402.setText("Tình trạng: Trống");

        ButtonP402.setBackground(new java.awt.Color(51, 51, 51));
        ButtonP402.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonP402.setForeground(new java.awt.Color(255, 255, 255));
        ButtonP402.setText("Đặt phòng");
        ButtonP402.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonP402ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnP402Layout = new javax.swing.GroupLayout(JpnP402);
        JpnP402.setLayout(JpnP402Layout);
        JpnP402Layout.setHorizontalGroup(
            JpnP402Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP402Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpnP402Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP402Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JpnP402Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP402Layout.createSequentialGroup()
                                .addComponent(MaPhongP402)
                                .addGap(103, 103, 103))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP402Layout.createSequentialGroup()
                                .addComponent(KieuPhongP402)
                                .addGap(49, 49, 49)))
                        .addGroup(JpnP402Layout.createSequentialGroup()
                            .addGroup(JpnP402Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(LoaiPhongP402)
                                .addComponent(TinhTrangP402))
                            .addGap(19, 19, 19)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP402Layout.createSequentialGroup()
                        .addComponent(ButtonP402)
                        .addGap(72, 72, 72))))
        );
        JpnP402Layout.setVerticalGroup(
            JpnP402Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP402Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaPhongP402)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(KieuPhongP402)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LoaiPhongP402)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TinhTrangP402)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonP402)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        JpnP403.setBackground(new java.awt.Color(250, 140, 0));

        MaPhongP403.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        MaPhongP403.setForeground(new java.awt.Color(255, 255, 255));
        MaPhongP403.setText("P403");

        KieuPhongP403.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        KieuPhongP403.setForeground(new java.awt.Color(255, 255, 255));
        KieuPhongP403.setText("Kiểu phòng: Giường đơn");

        LoaiPhongP403.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoaiPhongP403.setForeground(new java.awt.Color(255, 255, 255));
        LoaiPhongP403.setText("Loại phòng: VIP");

        TinhTrangP403.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TinhTrangP403.setForeground(new java.awt.Color(255, 255, 255));
        TinhTrangP403.setText("Tình trạng: Trống");

        ButtonP403.setBackground(new java.awt.Color(51, 51, 51));
        ButtonP403.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ButtonP403.setForeground(new java.awt.Color(255, 255, 255));
        ButtonP403.setText("Đặt phòng");
        ButtonP403.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonP403ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpnP403Layout = new javax.swing.GroupLayout(JpnP403);
        JpnP403.setLayout(JpnP403Layout);
        JpnP403Layout.setHorizontalGroup(
            JpnP403Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP403Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpnP403Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP403Layout.createSequentialGroup()
                        .addGroup(JpnP403Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpnP403Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(MaPhongP403))
                            .addComponent(LoaiPhongP403)
                            .addComponent(TinhTrangP403)
                            .addComponent(KieuPhongP403))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpnP403Layout.createSequentialGroup()
                        .addComponent(ButtonP403)
                        .addGap(75, 75, 75))))
        );
        JpnP403Layout.setVerticalGroup(
            JpnP403Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnP403Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MaPhongP403)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KieuPhongP403)
                .addGap(12, 12, 12)
                .addComponent(LoaiPhongP403)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TinhTrangP403)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonP403)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnP401, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnP402, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JpnP403, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnP401, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnP402, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JpnP403, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonP101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonP101ActionPerformed

        String maPhong=MaPhongP101.getText();
        String kieuPhongText=KieuPhongP101.getText();
        String kieuPhong="";
        String[] parts = kieuPhongText.split(":");
        if (parts.length > 1) {
            kieuPhong = parts[1].trim(); 
        }
        String loaiPhongText=LoaiPhongP101.getText();
        String loaiPhong = "";

        String[] part = loaiPhongText.split(":");
        if (part.length > 1) {
            loaiPhong = part[1].trim();  
}
        

        if(ButtonP101.getText()=="Đặt phòng") {       
            DatPhongForm dh=new DatPhongForm(JpnP101,maPhong,TinhTrangP101,ButtonP101,null,kieuPhong,loaiPhong);
            dh.setLocationRelativeTo(null);
            dh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dh.setVisible(true);
        }
        
        else {
            DatPhong x=phong.getPhongDangSuDung(MaPhongP101.getText());
            System.out.println(x.getTrangThai());
            this.TableDV=ctdichVu.createCTDichVuTable(x.getMaDatPhong());
            BillForm bill=new BillForm(maPhong,loaiPhong,kieuPhong,x.getMaDatPhong(),x.getMaKhachHang(),TableDV,JpnP101,TinhTrangP101,ButtonP101);
            bill.setLocationRelativeTo(null);
            bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bill.setVisible(true);
        }
    }//GEN-LAST:event_ButtonP101ActionPerformed

    private void ButtonP102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonP102ActionPerformed
               String maPhong=MaPhongP102.getText();
        String kieuPhongText=KieuPhongP102.getText();
        String kieuPhong="";
        String[] parts = kieuPhongText.split(":");
        if (parts.length > 1) {
            kieuPhong = parts[1].trim(); 
        }
        String loaiPhongText=LoaiPhongP102.getText();
        String loaiPhong = "";

        String[] part = loaiPhongText.split(":");
        if (part.length > 1) {
            loaiPhong = part[1].trim();  
}
        

        if(ButtonP102.getText()=="Đặt phòng") {       
            DatPhongForm dh=new DatPhongForm(JpnP102,maPhong,TinhTrangP102,ButtonP102,null,kieuPhong,loaiPhong);
            dh.setLocationRelativeTo(null);
            dh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dh.setVisible(true);
        }
        
        else {
            DatPhong x=phong.getPhongDangSuDung(MaPhongP102.getText());
            System.out.println(x.getTrangThai());
            this.TableDV=ctdichVu.createCTDichVuTable(x.getMaDatPhong());
            BillForm bill=new BillForm(maPhong,loaiPhong,kieuPhong,x.getMaDatPhong(),x.getMaKhachHang(),TableDV,JpnP102,TinhTrangP102,ButtonP102);
            bill.setLocationRelativeTo(null);
            bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bill.setVisible(true);
        }
    }//GEN-LAST:event_ButtonP102ActionPerformed

    private void ButtonP103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonP103ActionPerformed
        
        String maPhong=MaPhongP103.getText();
        String kieuPhongText=KieuPhongP103.getText();
        String kieuPhong="";
        String[] parts = kieuPhongText.split(":");
        if (parts.length > 1) {
            kieuPhong = parts[1].trim(); 
        }
        String loaiPhongText=LoaiPhongP103.getText();
        String loaiPhong = "";

        String[] part = loaiPhongText.split(":");
        if (part.length > 1) {
            loaiPhong = part[1].trim();  
}
        if(ButtonP103.getText()=="Đặt phòng") {       
            DatPhongForm dh=new DatPhongForm(JpnP103,maPhong,TinhTrangP103,ButtonP103,null,kieuPhong,loaiPhong);
            dh.setLocationRelativeTo(null);
            dh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dh.setVisible(true);
        }
        
        else {
            DatPhong x=phong.getPhongDangSuDung(MaPhongP103.getText());
            this.TableDV=ctdichVu.createCTDichVuTable(x.getMaDatPhong());
            BillForm bill=new BillForm(maPhong,loaiPhong,kieuPhong,x.getMaDatPhong(),x.getMaKhachHang(),TableDV,JpnP103,TinhTrangP103,ButtonP103);
            bill.setLocationRelativeTo(null);
            bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bill.setVisible(true);
        }
    }//GEN-LAST:event_ButtonP103ActionPerformed

    private void ButtonP201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonP201ActionPerformed

        String maPhong=MaPhongP201.getText();
        String kieuPhongText=KieuPhongP201.getText();
        String kieuPhong="";
        String[] parts = kieuPhongText.split(":");
        if (parts.length > 1) {
            kieuPhong = parts[1].trim(); 
        }
        String loaiPhongText=LoaiPhongP201.getText();
        String loaiPhong = "";

        String[] part = loaiPhongText.split(":");
        if (part.length > 1) {
            loaiPhong = part[1].trim();  
}
        if(ButtonP201.getText()=="Đặt phòng") {       
            DatPhongForm dh=new DatPhongForm(JpnP201,maPhong,TinhTrangP201,ButtonP201,null,kieuPhong,loaiPhong);
            dh.setLocationRelativeTo(null);
            dh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dh.setVisible(true);
        }
        
        else {
            DatPhong x=phong.getPhongDangSuDung(MaPhongP201.getText());
            this.TableDV=ctdichVu.createCTDichVuTable(x.getMaDatPhong());
            BillForm bill=new BillForm(maPhong,loaiPhong,kieuPhong,x.getMaDatPhong(),x.getMaKhachHang(),TableDV,JpnP201,TinhTrangP201,ButtonP201);
            bill.setLocationRelativeTo(null);
            bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bill.setVisible(true);
        }
    }//GEN-LAST:event_ButtonP201ActionPerformed

    private void ButtonP202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonP202ActionPerformed
        
                String maPhong=MaPhongP202.getText();
        String kieuPhongText=KieuPhongP202.getText();
        String kieuPhong="";
        String[] parts = kieuPhongText.split(":");
        if (parts.length > 1) {
            kieuPhong = parts[1].trim(); 
        }
        String loaiPhongText=LoaiPhongP202.getText();
        String loaiPhong = "";

        String[] part = loaiPhongText.split(":");
        if (part.length > 1) {
            loaiPhong = part[1].trim();  
}
        if(ButtonP202.getText()=="Đặt phòng") {       
            DatPhongForm dh=new DatPhongForm(JpnP202,maPhong,TinhTrangP202,ButtonP202,null,kieuPhong,loaiPhong);
            dh.setLocationRelativeTo(null);
            dh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dh.setVisible(true);
        }
        
        else {
            DatPhong x=phong.getPhongDangSuDung(MaPhongP202.getText());
            this.TableDV=ctdichVu.createCTDichVuTable(x.getMaDatPhong());
            BillForm bill=new BillForm(maPhong,loaiPhong,kieuPhong,x.getMaDatPhong(),x.getMaKhachHang(),TableDV,JpnP202,TinhTrangP202,ButtonP202);
            bill.setLocationRelativeTo(null);
            bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bill.setVisible(true);
        }
    }//GEN-LAST:event_ButtonP202ActionPerformed

    private void ButtonP203ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonP203ActionPerformed
                String maPhong=MaPhongP203.getText();
        String kieuPhongText=KieuPhongP203.getText();
        String kieuPhong="";
        String[] parts = kieuPhongText.split(":");
        if (parts.length > 1) {
            kieuPhong = parts[1].trim(); 
        }
        String loaiPhongText=LoaiPhongP203.getText();
        String loaiPhong = "";

        String[] part = loaiPhongText.split(":");
        if (part.length > 1) {
            loaiPhong = part[1].trim();  
}
        if(ButtonP203.getText()=="Đặt phòng") {       
            DatPhongForm dh=new DatPhongForm(JpnP203,maPhong,TinhTrangP203,ButtonP203,null,kieuPhong,loaiPhong);
            dh.setLocationRelativeTo(null);
            dh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dh.setVisible(true);
        }
        
        else {
            DatPhong x=phong.getPhongDangSuDung(MaPhongP203.getText());
            this.TableDV=ctdichVu.createCTDichVuTable(x.getMaDatPhong());
            BillForm bill=new BillForm(maPhong,loaiPhong,kieuPhong,x.getMaDatPhong(),x.getMaKhachHang(),TableDV,JpnP203,TinhTrangP203,ButtonP203);
            bill.setLocationRelativeTo(null);
            bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bill.setVisible(true);
        }
       
    }//GEN-LAST:event_ButtonP203ActionPerformed

    private void ButtonP301ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonP301ActionPerformed
        String maPhong=MaPhongP301.getText();
        String kieuPhongText=KieuPhongP301.getText();
        String kieuPhong="";
        String[] parts = kieuPhongText.split(":");
        if (parts.length > 1) {
            kieuPhong = parts[1].trim(); 
        }
        String loaiPhongText=LoaiPhongP301.getText();
        String loaiPhong = "";

        String[] part = loaiPhongText.split(":");
        if (part.length > 1) {
            loaiPhong = part[1].trim();  
}
        if(ButtonP301.getText()=="Đặt phòng") {       
            DatPhongForm dh=new DatPhongForm(JpnP301,maPhong,TinhTrangP301,ButtonP301,null,kieuPhong,loaiPhong);
            dh.setLocationRelativeTo(null);
            dh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dh.setVisible(true);
        }
        
        else {
            DatPhong x=phong.getPhongDangSuDung(MaPhongP301.getText());
            this.TableDV=ctdichVu.createCTDichVuTable(x.getMaDatPhong());
            BillForm bill=new BillForm(maPhong,loaiPhong,kieuPhong,x.getMaDatPhong(),x.getMaKhachHang(),TableDV,JpnP301,TinhTrangP301,ButtonP301);
            bill.setLocationRelativeTo(null);
            bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bill.setVisible(true);
        }
    }//GEN-LAST:event_ButtonP301ActionPerformed

    private void ButtonP302ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonP302ActionPerformed
        
                String maPhong=MaPhongP302.getText();
        String kieuPhongText=KieuPhongP302.getText();
        String kieuPhong="";
        String[] parts = kieuPhongText.split(":");
        if (parts.length > 1) {
            kieuPhong = parts[1].trim(); 
        }
        String loaiPhongText=LoaiPhongP302.getText();
        String loaiPhong = "";

        String[] part = loaiPhongText.split(":");
        if (part.length > 1) {
            loaiPhong = part[1].trim();  
}
        if(ButtonP302.getText()=="Đặt phòng") {       
            DatPhongForm dh=new DatPhongForm(JpnP302,maPhong,TinhTrangP302,ButtonP302,null,kieuPhong,loaiPhong);
            dh.setLocationRelativeTo(null);
            dh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dh.setVisible(true);
        }
        
        else {
            DatPhong x=phong.getPhongDangSuDung(MaPhongP302.getText());
            this.TableDV=ctdichVu.createCTDichVuTable(x.getMaDatPhong());
            BillForm bill=new BillForm(maPhong,loaiPhong,kieuPhong,x.getMaDatPhong(),x.getMaKhachHang(),TableDV,JpnP302,TinhTrangP302,ButtonP302);
            bill.setLocationRelativeTo(null);
            bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bill.setVisible(true);
        }
    }//GEN-LAST:event_ButtonP302ActionPerformed

    private void ButtonP303ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonP303ActionPerformed
        
                String maPhong=MaPhongP303.getText();
        String kieuPhongText=KieuPhongP303.getText();
        String kieuPhong="";
        String[] parts = kieuPhongText.split(":");
        if (parts.length > 1) {
            kieuPhong = parts[1].trim(); 
        }
        String loaiPhongText=LoaiPhongP303.getText();
        String loaiPhong = "";

        String[] part = loaiPhongText.split(":");
        if (part.length > 1) {
            loaiPhong = part[1].trim();  
}
        if(ButtonP303.getText()=="Đặt phòng") {       
            DatPhongForm dh=new DatPhongForm(JpnP303,maPhong,TinhTrangP303,ButtonP303,null,kieuPhong,loaiPhong);
            dh.setLocationRelativeTo(null);
            dh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dh.setVisible(true);
        }
        
        else {
            DatPhong x=phong.getPhongDangSuDung(MaPhongP303.getText());
            this.TableDV=ctdichVu.createCTDichVuTable(x.getMaDatPhong());
            BillForm bill=new BillForm(maPhong,loaiPhong,kieuPhong,x.getMaDatPhong(),x.getMaKhachHang(),TableDV,JpnP303,TinhTrangP303,ButtonP303);
            bill.setLocationRelativeTo(null);
            bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bill.setVisible(true);
        }
    }//GEN-LAST:event_ButtonP303ActionPerformed

    private void ButtonP401ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonP401ActionPerformed
        String maPhong=MaPhongP401.getText();
        String kieuPhongText=KieuPhongP401.getText();
        String kieuPhong="";
        String[] parts = kieuPhongText.split(":");
        if (parts.length > 1) {
            kieuPhong = parts[1].trim(); 
        }
        String loaiPhongText=LoaiPhongP401.getText();
        String loaiPhong = "";

        String[] part = loaiPhongText.split(":");
        if (part.length > 1) {
            loaiPhong = part[1].trim();  
}
        if(ButtonP401.getText()=="Đặt phòng") {       
            DatPhongForm dh=new DatPhongForm(JpnP401,maPhong,TinhTrangP401,ButtonP401,null,kieuPhong,loaiPhong);
            dh.setLocationRelativeTo(null);
            dh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dh.setVisible(true);
        }
        
        else {
            DatPhong x=phong.getPhongDangSuDung(MaPhongP401.getText());
            this.TableDV=ctdichVu.createCTDichVuTable(x.getMaDatPhong());
            BillForm bill=new BillForm(maPhong,loaiPhong,kieuPhong,x.getMaDatPhong(),x.getMaKhachHang(),TableDV,JpnP401,TinhTrangP401,ButtonP401);
            bill.setLocationRelativeTo(null);
            bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bill.setVisible(true);
        }
    }//GEN-LAST:event_ButtonP401ActionPerformed

    private void ButtonP402ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonP402ActionPerformed
        
                String maPhong=MaPhongP402.getText();
        String kieuPhongText=KieuPhongP402.getText();
        String kieuPhong="";
        String[] parts = kieuPhongText.split(":");
        if (parts.length > 1) {
            kieuPhong = parts[1].trim(); 
        }
        String loaiPhongText=LoaiPhongP402.getText();
        String loaiPhong = "";

        String[] part = loaiPhongText.split(":");
        if (part.length > 1) {
            loaiPhong = part[1].trim();  
}
        if(ButtonP402.getText()=="Đặt phòng") {       
            DatPhongForm dh=new DatPhongForm(JpnP402,maPhong,TinhTrangP402,ButtonP402,null,kieuPhong,loaiPhong);
            dh.setLocationRelativeTo(null);
            dh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dh.setVisible(true);
        }
        
        else {
            DatPhong x=phong.getPhongDangSuDung(MaPhongP402.getText());
            this.TableDV=ctdichVu.createCTDichVuTable(x.getMaDatPhong());
            BillForm bill=new BillForm(maPhong,loaiPhong,kieuPhong,x.getMaDatPhong(),x.getMaKhachHang(),TableDV,JpnP402,TinhTrangP402,ButtonP402);
            bill.setLocationRelativeTo(null);
            bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bill.setVisible(true);
        }
    }//GEN-LAST:event_ButtonP402ActionPerformed

    private void ButtonP403ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonP403ActionPerformed
        
               String maPhong=MaPhongP403.getText();
        String kieuPhongText=KieuPhongP403.getText();
        String kieuPhong="";
        String[] parts = kieuPhongText.split(":");
        if (parts.length > 1) {
            kieuPhong = parts[1].trim(); 
        }
        String loaiPhongText=LoaiPhongP403.getText();
        String loaiPhong = "";

        String[] part = loaiPhongText.split(":");
        if (part.length > 1) {
            loaiPhong = part[1].trim();  
}
        if(ButtonP403.getText()=="Đặt phòng") {       
            DatPhongForm dh=new DatPhongForm(JpnP403,maPhong,TinhTrangP403,ButtonP403,null,kieuPhong,loaiPhong);
            dh.setLocationRelativeTo(null);
            dh.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            dh.setVisible(true);
        }
        
        else {
            DatPhong x=phong.getPhongDangSuDung(MaPhongP403.getText());
            this.TableDV=ctdichVu.createCTDichVuTable(x.getMaDatPhong());
            BillForm bill=new BillForm(maPhong,loaiPhong,kieuPhong,x.getMaDatPhong(),x.getMaKhachHang(),TableDV,JpnP403,TinhTrangP403,ButtonP403);
            bill.setLocationRelativeTo(null);
            bill.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            bill.setVisible(true);
        }
    }//GEN-LAST:event_ButtonP403ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonP101;
    private javax.swing.JButton ButtonP102;
    private javax.swing.JButton ButtonP103;
    private javax.swing.JButton ButtonP201;
    private javax.swing.JButton ButtonP202;
    private javax.swing.JButton ButtonP203;
    private javax.swing.JButton ButtonP301;
    private javax.swing.JButton ButtonP302;
    private javax.swing.JButton ButtonP303;
    private javax.swing.JButton ButtonP401;
    private javax.swing.JButton ButtonP402;
    private javax.swing.JButton ButtonP403;
    private javax.swing.JPanel JpnP101;
    private javax.swing.JPanel JpnP102;
    private javax.swing.JPanel JpnP103;
    private javax.swing.JPanel JpnP201;
    private javax.swing.JPanel JpnP202;
    private javax.swing.JPanel JpnP203;
    private javax.swing.JPanel JpnP301;
    private javax.swing.JPanel JpnP302;
    private javax.swing.JPanel JpnP303;
    private javax.swing.JPanel JpnP401;
    private javax.swing.JPanel JpnP402;
    private javax.swing.JPanel JpnP403;
    private javax.swing.JLabel KieuPhongP101;
    private javax.swing.JLabel KieuPhongP102;
    private javax.swing.JLabel KieuPhongP103;
    private javax.swing.JLabel KieuPhongP201;
    private javax.swing.JLabel KieuPhongP202;
    private javax.swing.JLabel KieuPhongP203;
    private javax.swing.JLabel KieuPhongP301;
    private javax.swing.JLabel KieuPhongP302;
    private javax.swing.JLabel KieuPhongP303;
    private javax.swing.JLabel KieuPhongP401;
    private javax.swing.JLabel KieuPhongP402;
    private javax.swing.JLabel KieuPhongP403;
    private javax.swing.JLabel LoaiPhongP101;
    private javax.swing.JLabel LoaiPhongP102;
    private javax.swing.JLabel LoaiPhongP103;
    private javax.swing.JLabel LoaiPhongP201;
    private javax.swing.JLabel LoaiPhongP202;
    private javax.swing.JLabel LoaiPhongP203;
    private javax.swing.JLabel LoaiPhongP301;
    private javax.swing.JLabel LoaiPhongP302;
    private javax.swing.JLabel LoaiPhongP303;
    private javax.swing.JLabel LoaiPhongP401;
    private javax.swing.JLabel LoaiPhongP402;
    private javax.swing.JLabel LoaiPhongP403;
    private javax.swing.JLabel MaPhongP101;
    private javax.swing.JLabel MaPhongP102;
    private javax.swing.JLabel MaPhongP103;
    private javax.swing.JLabel MaPhongP201;
    private javax.swing.JLabel MaPhongP202;
    private javax.swing.JLabel MaPhongP203;
    private javax.swing.JLabel MaPhongP301;
    private javax.swing.JLabel MaPhongP302;
    private javax.swing.JLabel MaPhongP303;
    private javax.swing.JLabel MaPhongP401;
    private javax.swing.JLabel MaPhongP402;
    private javax.swing.JLabel MaPhongP403;
    private javax.swing.JLabel TinhTrangP101;
    private javax.swing.JLabel TinhTrangP102;
    private javax.swing.JLabel TinhTrangP103;
    private javax.swing.JLabel TinhTrangP201;
    private javax.swing.JLabel TinhTrangP202;
    private javax.swing.JLabel TinhTrangP203;
    private javax.swing.JLabel TinhTrangP301;
    private javax.swing.JLabel TinhTrangP302;
    private javax.swing.JLabel TinhTrangP303;
    private javax.swing.JLabel TinhTrangP401;
    private javax.swing.JLabel TinhTrangP402;
    private javax.swing.JLabel TinhTrangP403;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
