/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import view.EmailSender1;

/**
 *
 * @author Admin
 */
public class QuenMatKhau1 extends javax.swing.JFrame {

    /**
     * Creates new form QuenMatKhau
     */
    public QuenMatKhau1() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ForgotPassword1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ForgotPassword = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("Forgot password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 19, 167, 42));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Send to Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 122, 20));

        ForgotPassword1.setBackground(new java.awt.Color(255, 255, 204));
        ForgotPassword1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ForgotPassword1.setPreferredSize(new java.awt.Dimension(64, 30));
        ForgotPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgotPassword1ActionPerformed(evt);
            }
        });
        jPanel1.add(ForgotPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 310, 20));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 110, 32));

        jLabel3.setText("OTP");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 60, 10));

        ForgotPassword.setBackground(new java.awt.Color(255, 255, 204));
        ForgotPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        ForgotPassword.setPreferredSize(new java.awt.Dimension(64, 30));
        ForgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgotPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(ForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 310, 20));

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setText("Verify");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 110, 32));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ForgotPassword1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotPassword1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForgotPassword1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String email = ForgotPassword.getText().trim();

    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập email");
        return;
    }

    // Sinh mã OTP giả sử
     generatedOTP = String.valueOf((int)(Math.random() * 900000) + 100000);

    String subject = "Mã xác nhận đổi mật khẩu";
    String content = "Mã OTP của bạn là: " + generatedOTP;

    boolean result = EmailSender1.sendEmail(email, subject, content);
    if (result) {
        JOptionPane.showMessageDialog(this, "Đã gửi mã OTP đến email của bạn!");
        // Lưu OTP vào biến toàn cục hoặc mở form nhập OTP nếu muốn
    } else {
        JOptionPane.showMessageDialog(this, "Gửi email thất bại. Vui lòng kiểm tra lại.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ForgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgotPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ForgotPasswordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String userOTP = ForgotPassword1.getText().trim();

    if (userOTP.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập mã OTP");
        return;
    }

    if (generatedOTP != null && userOTP.equals(generatedOTP)) {
        JOptionPane.showMessageDialog(this, "Xác minh thành công! Bạn có thể đổi mật khẩu.");
        // TODO: mở form đổi mật khẩu hoặc cho phép tiếp tục
     ManHinhDoiMatKhau1 doiMatKhauForm = new ManHinhDoiMatKhau1(ForgotPassword.getText().trim());
    
    doiMatKhauForm.setLocationRelativeTo(this);
    doiMatKhauForm.setVisible(true);
    this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Mã OTP không đúng. Vui lòng thử lại.");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuenMatKhau1().setVisible(true);
            }
        });
    }
    
    private String generatedOTP;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ForgotPassword;
    private javax.swing.JTextField ForgotPassword1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
